# Form implementation generated from reading ui file 'designer\import_dictionary.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.chooseFileButton = QtWidgets.QPushButton(Dialog)
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chooseFileButton)
        self.dictionaryComboBox = QtWidgets.QComboBox(Dialog)
        self.dictionaryComboBox.setObjectName("dictionaryComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dictionaryComboBox)
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.addButton)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.dictionaryNameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.dictionaryNameLineEdit.setObjectName("dictionaryNameLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dictionaryNameLineEdit)
        self.description = QtWidgets.QLabel(Dialog)
        self.description.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.description.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.description.setObjectName("description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.description)
        self.filenameLabel = QtWidgets.QLabel(Dialog)
        self.filenameLabel.setText("")
        self.filenameLabel.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.filenameLabel.setObjectName("filenameLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.filenameLabel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Wiktionary - Import a dictionary"))
        self.label_3.setText(_translate("Dialog", "Dictionary"))
        self.chooseFileButton.setText(_translate("Dialog", "Choose file"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.label.setText(_translate("Dialog", "Dictionary file"))
        self.label_2.setText(_translate("Dialog", "Dictionary name"))
        self.description.setText(_translate("Dialog", "Description"))
