# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/import_dictionary.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description = QtWidgets.QLabel(Dialog)
        self.description.setTextFormat(QtCore.Qt.RichText)
        self.description.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByMouse
        )
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.chooseFileButton = QtWidgets.QPushButton(self.widget)
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.chooseFileButton
        )
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dictionaryNameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.dictionaryNameLineEdit.setObjectName("dictionaryNameLineEdit")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.dictionaryNameLineEdit
        )
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.addButton)
        self.filenameLabel = QtWidgets.QLabel(self.widget)
        self.filenameLabel.setText("")
        self.filenameLabel.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByMouse
        )
        self.filenameLabel.setObjectName("filenameLabel")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.SpanningRole, self.filenameLabel
        )
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Wiktionary - Import a dictionary"))
        self.description.setText(_translate("Dialog", "Description"))
        self.label.setText(_translate("Dialog", "Dictionary file"))
        self.chooseFileButton.setText(_translate("Dialog", "Choose file"))
        self.label_2.setText(_translate("Dialog", "Dictionary name"))
        self.addButton.setText(_translate("Dialog", "Add"))
